TD-3 Created TodoService
samokisha/todo-list-app pull request #7
Opened 2023-02-27 19:13 UTC by MrKrodbon

2023-03-05 11:08 UTC, samokisha requested changes
Також пройдись по всім файлам та виправ стиль коду.
Пустий рядок між методами, конструкторами, блоком проперті, namespaces і т.д.
Видалити не потрібні пусті рядки в пустих конструкторах та в кінці блоків {}.
Не треба додавати більше ніж 1 пустий рядок підряд.

2023-03-05 11:08 UTC, samokisha commented on src/ToDoList.Api/appsettings.json
> +  },
Api сервіс не буде ходити напряму в БД. Видаляємо.

2023-03-05 11:08 UTC, samokisha commented on src/ToDoList.Api/ToDoList.Api.csproj
> +    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.17.0" />
Видаляємо все що повʼязано з БД в Api сервісі.

2023-03-05 11:08 UTC, samokisha commented on src/ToDoList.Api/ToDoList.Api.csproj
> +    <ProjectReference Include="..\..\TodoService\TodoService.csproj" />
Api не повинно залежати від сервіса.

2023-03-05 11:08 UTC, samokisha commented on src/ToDoList.Api/ToDoList.Api.csproj
> +    <DockerDefaultTargetOS>Windows</DockerDefaultTargetOS>
На серверах панує linux. Міняємо на Linux.

2023-03-05 11:08 UTC, samokisha commented on src/ToDoList.Api/Program.cs
> +    x.AddRequestClient<ToDoItem>();
Через RabbitMQ повинні ходити request і response моделі

2023-03-05 11:08 UTC, samokisha commented on src/ToDoList.Api/Program.cs
> +        configurator.Host("RabbitMQ");
hostname як і домен url прийнято писати lowercase. Хоча він case insensitive.

2023-03-05 11:08 UTC, samokisha commented on src/ToDoList.Api/Program.cs
> +
Зберігаємо код чистим та перевіряємо те що комітимо.
Видаляй непотрібні пусті рядки.

2023-03-05 11:08 UTC, samokisha commented on src/ToDoList.Api/Dockerfile
> +COPY ["TodoService/TodoService.csproj", "TodoService/"]
Видаляємо залежність від сервісу

2023-03-05 11:08 UTC, samokisha commented on ToDoList.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "TodoService", "TodoService\TodoService.csproj", "{791DE60B-D68B-4AA2-A141-02F8741EF766}"
Всі проекти повинні бути в src директорії.
Перемісти директорію з проектом та виправ шлях тут.

2023-03-05 11:08 UTC, samokisha commented on docker-compose.dcproj
> +    <DockerTargetOS>Windows</DockerTargetOS>
Linux

2023-03-05 11:08 UTC, samokisha commented on docker-compose.yml
> +  todoservice:
Додай пустий рядок між сервісами

2023-03-05 11:08 UTC, samokisha commented on docker-compose.yml
> +  todolist.api:
В файлі docker-compose.yml визначаються параметри збірки контейнера сервісу. Параметри старту сервісу повинні визначатися в файлі docker-compose.override.yml
Перенеси сервіси rabbitmq і sql-server в docker-compose.override.yml.
Параметри ports та depends_on відносяться до параметрів старту. Виправ для todolist.api і todoservice

2023-03-05 11:08 UTC, samokisha commented on docker-compose.yml
> +        condition: service_started
Api не повинно залежати від БД

2023-03-05 11:08 UTC, samokisha commented on docker-compose.yml
> +        condition: service_started
Чому сервіс залежить від Api? Йому не потрібно Api для роботи. Він обробляє запити з черги маніпулюючи даними в БД. Подумай які в нього залежності.

2023-03-05 11:08 UTC, samokisha commented on TodoService/Consumers/ToDoDeleteConsumer.cs
> +    public async Task Consume(ConsumeContext<ToDoItem> context)
Приймаємо requestModel, віддаємо responseModel. Сутність БД  не повинна виходити за рамки менеджера.
Пустий рядок між методами.

Те саме стосується інших консюмерів.

2023-03-05 11:08 UTC, samokisha commented on TodoService/Consumers/ToDoDeleteConsumer.cs
> +public class ToDoDeleteConsumer : IConsumer<ToDoItem>
Пустий рядок

2023-03-05 11:08 UTC, samokisha commented on TodoService/Data/Entities/TodoItem.cs
> +public class ToDoItem
Пустий рядок

2023-03-05 11:08 UTC, samokisha commented on TodoService/Data/ToDoContext.cs
> +            .IsRequired();
Додай обмеження по розміру для імені (128)

2023-03-05 11:08 UTC, samokisha commented on TodoService/Managers/ToDoManager.cs
> +        await _toDoContext.SaveChangesAsync(cancellationToken);
Перед тим як зберігати, потрібно додати дані до DbSet.
Подумай що повинен робити кожен з методів ToDoManager та реалізуй це.

2023-03-05 11:08 UTC, samokisha commented on TodoService/Program.cs
> +
Не потрібно зберігати сміття

2023-03-05 11:08 UTC, samokisha commented on TodoService/TodoService.csproj
> +    <DockerDefaultTargetOS>Windows</DockerDefaultTargetOS>
Linux

2023-03-05 11:08 UTC, samokisha commented on TodoService/Program.cs
> +});
Це повинно бути вище в ConfigureServices. Також не вистачає .AddMassTransitHostedService()

2023-03-05 11:08 UTC, samokisha commented on TodoService/Program.cs
> +        services.AddHostedService<Worker>();
Не потрібно, як і клас Worker

2023-03-24 20:58 UTC, samokisha requested changes

2023-03-24 20:58 UTC, samokisha commented on docker-compose.override.yml
> +      - C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:/appdata/ASP.NET/Https
Це copy/paste з інтернету? Чи ти реально в windows підписаний як "ContainerUser"?

2023-03-24 20:58 UTC, samokisha commented on src/TodoService/Consumers/ToDoDeleteConsumer.cs
> +        await _toDoManager.DeleteAsync((ToDoDeleteRequestModel)context, context.CancellationToken);
- `_toDoManager = null`
- Навіщо тут кастинг `(ToDoDeleteRequestModel)context` ?

2023-03-24 20:58 UTC, samokisha commented on src/TodoService/Consumers/ToDoDeleteConsumer.cs
>              Id = context.Message.Id
Який сенс повертати те, що прийшло в запиті?

2023-03-24 20:58 UTC, samokisha commented on src/TodoService/Consumers/ToDoGetConsumer.cs
>              Id = context.Message.Id
Тобто я хочу отримати todo з БД за його id, але у відповідь отримую ту саму id. Чи не здається тобі, що тут щось не так?

2023-03-24 20:58 UTC, samokisha commented on src/TodoService/Consumers/ToDoPostConsumer.cs
>              Name = $"Name of task {context.Message.Name}",
Це звичайно неймовірно, що я отримаю у відповідь пояснення що "Name of tast {passed Name}" та "Description of task{passed Description}". Але здається я не цього очікую.

2023-03-24 20:58 UTC, samokisha commented on src/TodoService/Consumers/ToDoPutConsumer.cs
>              Name = $"Name of task {context.Message.Name}",
Те саме, що при створенні

2023-03-24 20:58 UTC, samokisha commented on src/TodoService/Managers/ToDoManager.cs
> +    private ToDoItem? _searchItemResult;
Навіщо це приватне поле? Чим не влаштовує локальна змінна?

2023-03-24 20:58 UTC, samokisha commented on src/TodoService/Managers/ToDoManager.cs
> +        using (_toDoContext)
Навіщо тут using?

2023-03-24 20:58 UTC, samokisha commented on src/TodoService/Managers/ToDoManager.cs
> +            };
Чогось тут не вистачає. Чогось, за допомогою чого ми зможемо далі працювати з сутністю.

2023-03-24 20:58 UTC, samokisha commented on src/TodoService/Managers/ToDoManager.cs
> +            await _toDoContext.SaveChangesAsync(cancellationToken);
Що тут відбувається? Поясни кожен рядок коду.

2023-03-24 20:58 UTC, samokisha commented on src/TodoService/Managers/ToDoManager.cs
> +                await _toDoContext.SaveChangesAsync(cancellationToken);
Що тут відбувається? Поясни кожен рядок коду.

2023-03-24 21:35 UTC, MrKrodbon commented on src/TodoService/Consumers/ToDoDeleteConsumer.cs
> +        await _toDoManager.DeleteAsync((ToDoDeleteRequestModel)context, context.CancellationToken);
Бо без нього він не розуміє, до якого типу відноситься

2023-03-24 21:37 UTC, MrKrodbon commented on src/TodoService/Managers/ToDoManager.cs
> +        using (_toDoContext)
Щоб закривати відкрите з'єднання з базою данних та очищувати ресурси після використання

2023-03-24 23:12 UTC, samokisha commented on src/TodoService/Consumers/ToDoDeleteConsumer.cs
> +        await _toDoManager.DeleteAsync((ToDoDeleteRequestModel)context, context.CancellationToken);
- _toDoManager потрібно заінжектити
- Те що метод не може прийняти параметр context з типом ConsumeContext<ToDoDeleteRequestModel>, каже що він не може з ним працювати. (ToDoDeleteRequestModel)context - це бомба яка спрацює в runtime і ти отримаєш InvalidCastException. Спробуй context.Message.

2023-03-24 23:12 UTC, samokisha commented on src/TodoService/Managers/ToDoManager.cs
> +        using (_toDoContext)
Ніколи не треба диспосити DbContext. Не ми його створювали, не нам його вбивати.

2023-03-25 16:12 UTC, MrKrodbon commented on src/TodoService/Managers/ToDoManager.cs
> +            await _toDoContext.SaveChangesAsync(cancellationToken);
На 58 строчці коду пошук елементу по айді який має оновлюватись
На 59 строчці коду саме оновлення в моделі що передається в параметрах
На 60 строчці коду збереження змін і передача токену для завершення процесу

2023-03-25 16:14 UTC, MrKrodbon commented on src/TodoService/Managers/ToDoManager.cs
> +                await _toDoContext.SaveChangesAsync(cancellationToken);
На 58 строчці коду пошук елементу по айді який має видалятись
На 59 строчці коду саме видалення елементу в моделі що передається в параметрах
На 60 строчці коду збереження змін і передача токену для завершення процесу

2023-03-25 16:57 UTC, samokisha commented on src/TodoService/Managers/ToDoManager.cs
> +            await _toDoContext.SaveChangesAsync(cancellationToken);
DbContext нічого не знає про request model. Для оновлення сутності в БД, потрібно її отримати з БД, перевірити чи отримали сутність з БД (не null), потім оновити в ній всі поля згідно отриманої request model окрім id (id ніколи не міняється) і викликати метод SaveChanges.

2023-03-25 17:25 UTC, samokisha commented on src/TodoService/Managers/ToDoManager.cs
> +                await _toDoContext.SaveChangesAsync(cancellationToken);
Щоб видалити сутність з БД, є два підходи.
Перший, пошук, перевірка на null, видалення.
```
var itemToRemove = await _toDoContext.TodoItem.FirstOrDefaultAsync(x => x.Id == deleteRequestModel.Id, cancellationToken);
if (itemToRemove != null)
{
    _toDoContext.Remove(itemToRemove);
    await _toDoContext.SaveChangesAsync(cancellationToken);
}
```
У цьому варіанті, ми спочатку отримуємо сутність, що потрібно видалити, за допомогою методу FirstOrDefaultAsync, який шукає сутність з вказаним Id. Якщо сутність була знайдена, ми викликаємо метод Remove для видалення цієї сутності з контексту, та зберігаємо зміни в базі даних за допомогою методу SaveChangesAsync. Якщо сутності з вказаним Id не знайдено, то жодної дії не буде виконано.

Другий, створення об'єкта сутності з його primary key, прив'язка, видалення.
```
var itemToRemove = new ToDoItem { Id = deleteRequestModel.Id };
_toDoContext.Attach(itemToRemove);
_toDoContext.Remove(itemToRemove);
await _toDoContext.SaveChangesAsync(cancellationToken);
```
У цьому варіанті ми створюємо новий об'єкт ToDoItem лише з його Id, а потім прив'язуємо його до контексту бази даних за допомогою методу Attach. Потім викликаємо метод Remove для видалення цієї сутності з контексту, та зберігаємо зміни в базі даних за допомогою методу SaveChangesAsync. Якщо сутності з вказаним Id не існує в базі даних, то виклик методу Attach не викличе помилку, але при спробі виклику методу Remove буде згенеровано виключення.

Другий варіант кращий, тому що ходить в БД лише раз. Для уникнення ситуації відсутності сутності в БД у майбутньому додамо валідацію. Зараз про це не треба турбуватися.

2023-04-09 12:54 UTC, samokisha requested changes

2023-04-09 12:54 UTC, samokisha commented on ToDoList.sln.bak
Це якийсь локальний бекап sln файлу. Не потрібний, видаляй.

2023-04-09 12:54 UTC, samokisha commented on docker-compose.override.yml
> +  todoservice:
Якщо todolist.api, то давай і тут буде todolist.service. Або todo.api і todo.service.

2023-04-09 12:54 UTC, samokisha commented on docker-compose.override.yml
> +      DefaultConnection: "Server=sql-server;Database=ToDoList;User Id=sa; Password=Todolist24app;TrustServerCertificate=True"
Змінні оточення давай іменувати як прийнято в unix системах UPPER_SNAKE_CASE.
Як ASPNETCORE_ENVIRONMENT і ASPNETCORE_URLS.

2023-04-09 12:54 UTC, samokisha commented on docker-compose.yml
> +    image: ${DOCKER_REGISTRY-}todoservice
Не забудь перейменувати image згідно імені сервісу.

2023-04-09 12:54 UTC, samokisha commented on src/ToDoList.Api/ToDoList.Api.csproj
> +	  <ProjectReference Include="..\TodoService\TodoService.csproj" />
Апі не повинна знати про сервіс, видаляємо.

2023-04-09 12:54 UTC, samokisha commented on src/TodoService/Consumers/ToDoDeleteConsumer.cs
> +    }
Розділяємо поля класу, конструктор та методи пустим рядком. Переглянь по всьому коду.

2023-04-09 12:54 UTC, samokisha commented on src/TodoService/Data/Entities/TodoItem.cs
> +    public string? Name { get; set; }
Імʼя обовʼязкове, не null.

2023-04-09 12:54 UTC, samokisha commented on src/TodoService/Data/ToDoContext.cs
> +
Лишній пустий рядок

2023-04-09 12:54 UTC, samokisha commented on src/TodoService/Managers/SearchItemResult.cs
Йому місце в моделях.

2023-04-09 12:54 UTC, samokisha commented on src/TodoService/Managers/ToDoManager.cs
> +    public async Task<ToDoItemResponseModel> PostAsync(ToDoCreateRequestModel createRequestModel, CancellationToken cancellationToken)
Менеджер не контролер, він працює з БД. Перейменуй  методи в Create і Update.

2023-04-09 12:54 UTC, samokisha commented on src/TodoService/Managers/ToDoManager.cs
> +        var searchItemResult = await _toDoContext.Set<ToDoItem>().FindAsync(readRequestModel.Id);
Чому не _toDoContext.TodoItem ?

2023-04-09 12:54 UTC, samokisha commented on src/TodoService/Managers/SearchItemResult.cs
> +internal class SearchRequestResult : ToDoItemResponseModel
Це що таке SearchRequestResult : ToDoItemResponseModel ?
Навіщо?

2023-04-09 12:54 UTC, samokisha commented on src/TodoService/Managers/ToDoManager.cs
> +            _toDoContext.Entry(updateItemResult).CurrentValues.SetValues(updateRequestModel);
Щось не зрозуміле. Спочатку дістаєш з БД, потім модифікуєш і зберігаєш.

2023-04-09 12:54 UTC, samokisha commented on src/TodoService/Managers/ToDoManager.cs
> +            };
Це не пошук, тут це не потрібно.
Поки що не потрібно перейматися валідацією та наявністю даних в БД. Це буде наступна задача.

2023-04-11 18:55 UTC, MrKrodbon commented on src/TodoService/Managers/SearchItemResult.cs
> +internal class SearchRequestResult : ToDoItemResponseModel
Це в мене була думка, що null значення записувались б в цей SearchRequestResult тому я віднаслідувався від ToDoItemResponseModel  але в цьому насправді немає сенсу так як в мене має бути лише одне поле яке й приймає null, зрозумів)

2023-04-11 18:56 UTC, MrKrodbon commented on src/TodoService/Managers/ToDoManager.cs
> +            _toDoContext.Entry(updateItemResult).CurrentValues.SetValues(updateRequestModel);
Я намагався дістати об'єкт що вже існує і модифікувати його, таким чином я розумію сам процес оновлення)

2023-04-11 19:04 UTC, samokisha commented on src/TodoService/Managers/ToDoManager.cs
> +            _toDoContext.Entry(updateItemResult).CurrentValues.SetValues(updateRequestModel);
Щоб дістати існуючу сутність з БД, потрібно через db context у потрібного db set, він у тебе лиш один, використовуючи FirstOrDefault, або SingleOrDefault якщо дістаєш по унікальному id.
Перевірити що не null, а потім міняти.

2023-04-23 09:23 UTC, samokisha requested changes

2023-04-23 09:23 UTC, samokisha commented on src/ToDoList.Api/Controllers/ToDoController.cs
> +using ToDoService.Managers;
Чому апі знову залежна від сервісу? Апі та сервіс повинні залежати від збірки з моделями, але не повинні один від одного.

2023-04-23 09:23 UTC, samokisha commented on src/ToDoList.Api/Controllers/ToDoController.cs
> +            return NotFound(response.ResponseModel);
Якщо `response.ResponseModel == null`, то немає сенсу його передавати в `NotFound`.

2023-04-23 09:23 UTC, samokisha commented on src/ToDoList.Api/Controllers/ToDoController.cs
> +            return NotFound(response.ResponseModel);
Якщо `response.ResponseModel == null`, то немає сенсу його передавати в `NotFound`.

2023-04-23 09:23 UTC, samokisha commented on src/ToDoList.Models/Responses/SearchRequestResultModel.cs
>  namespace ToDoService.Managers;
Перемістив в іншу збірку, а namespace не виправив. Він тепер вводить в оману.

2023-04-23 09:23 UTC, samokisha commented on src/TodoService/Consumers/ToDoDeleteConsumer.cs
> +        }
Вийшло так, що коли `result == null`, то консюмер не дасть відповіді. І зі сторони запиту, в даному випадку з контролера, буде TimeoutException.

Консюмер завжди повинен відповісти на запит.

Подумай що можна зробити.

2023-04-23 09:23 UTC, samokisha commented on src/TodoService/Managers/ToDoManager.cs
> +    public async Task<SearchRequestResultModel> Read(ToDoReadRequestModel readRequestModel, CancellationToken cancellationToken)
Чому повертається `SearchRequestResultModel`, а не `ToDoItemResponseModel`?

2023-04-23 09:23 UTC, samokisha commented on src/TodoService/Managers/ToDoManager.cs
> +    public async Task<SearchRequestResultModel> Update(ToDoUpdateRequestModel updateRequestModel, CancellationToken cancellationToken)
Чому повертається `SearchRequestResultModel`, а не `ToDoItemResponseModel`?

2023-04-23 09:23 UTC, samokisha commented on src/TodoService/Managers/ToDoManager.cs
> +            _toDoContext.Update(updateItemResult);
Це не потрібно. Ти вже змінив сутність з `_toDoContext.TodoItem`. Достатньо `_toDoContext.SaveChangesAsync` після зміни сутності.

2023-04-23 16:06 UTC, MrKrodbon commented on src/TodoService/Managers/ToDoManager.cs
> +    public async Task<SearchRequestResultModel> Read(ToDoReadRequestModel readRequestModel, CancellationToken cancellationToken)
Повертатись SearchRequestResultModel має саме в асинхронній відповіді консьюмера, так?
Де він передається назад до контролера і там я здійснюю перевірку

2023-04-30 19:18 UTC, samokisha requested changes

2023-04-30 19:18 UTC, samokisha commented on src/TodoService/Managers/ToDoManager.cs
> +    public async Task<ToDoItemResponseModel> Create(ToDoCreateRequestModel createRequestModel, CancellationToken cancellationToken)
Не забувай асинхронним методам додавати суфікс `Async`

2023-04-30 19:18 UTC, samokisha commented on src/TodoService/Managers/ToDoManager.cs
> +    public async Task<ToDoItemResponseModel?> Read(ToDoReadRequestModel readRequestModel, CancellationToken cancellationToken)
Не забувай асинхронним методам додавати суфікс `Async`

2023-04-30 19:18 UTC, samokisha commented on src/TodoService/Managers/ToDoManager.cs
> +        }
Давай спростимо.
В if потрібно лише присвоїти змінній toDoItemResponseModel значення. А після if повернути toDoItemResponseModel.

2023-04-30 19:18 UTC, samokisha commented on src/TodoService/Managers/ToDoManager.cs
> +    public async Task<ToDoItemResponseModel?> Update(ToDoUpdateRequestModel updateRequestModel, CancellationToken cancellationToken)
Не забувай асинхронним методам додавати суфікс `Async`

2023-04-30 19:18 UTC, samokisha commented on src/TodoService/Managers/ToDoManager.cs
> +    public async Task<ToDoDeleteResponseModel> Delete(ToDoDeleteRequestModel deleteRequestModel, CancellationToken cancellationToken)
Не забувай асинхронним методам додавати суфікс `Async`

2023-04-30 19:18 UTC, samokisha commented on src/TodoService/Managers/ToDoManager.cs
> +        }
Давай спростимо.
В if потрібно присвоїти змінній toDoItemResponseModel значення. А після if повернути toDoItemResponseModel.

2023-04-30 19:18 UTC, samokisha commented on src/TodoService/Consumers/ToDoPostConsumer.cs
> +        });
Не потрібно перемаплювати ToDoItemResponseModel в ToDoItemResponseModel.

2023-04-30 19:18 UTC, samokisha commented on src/ToDoList.Api/Controllers/ToDoController.cs
> +    public async Task<IActionResult> Post([FromBody] ToDoCreateRequestModel createRequestModel)
Не забувай асинхронним методам додавати суфікс `Async`

2023-04-30 19:18 UTC, samokisha commented on src/ToDoList.Api/Controllers/ToDoController.cs
> +        if (response != null)
Ніколи не буде null

2023-04-30 19:18 UTC, samokisha commented on src/ToDoList.Api/Controllers/ToDoController.cs
> +    public async Task<IActionResult> Get([FromQuery] ToDoReadRequestModel readRequestModel)
Не забувай асинхронним методам додавати суфікс `Async`

2023-04-30 19:18 UTC, samokisha commented on src/ToDoList.Api/Controllers/ToDoController.cs
> +    public async Task<IActionResult> Put([FromBody] ToDoUpdateRequestModel updateRequestModel)
Не забувай асинхронним методам додавати суфікс `Async`

2023-04-30 19:18 UTC, samokisha commented on src/ToDoList.Api/Controllers/ToDoController.cs
> +    public async Task<IActionResult> Delete([FromBody] ToDoDeleteRequestModel deleteRequestModel)
Не забувай асинхронним методам додавати суфікс `Async`

2023-04-30 19:18 UTC, samokisha commented on src/ToDoList.Api/Controllers/ToDoController.cs
> +            return Ok(response);
Просто Ok()

2023-05-07 17:15 UTC, samokisha commented on src/TodoService/Managers/ToDoManager.cs
> +        }
Прочитай ще раз що написано в коментарі вище, подивися як в методі UpdateAsync нижче та виправ.

2023-05-09 17:37 UTC, samokisha approved these changes

2023-05-09 17:50 UTC, merged